Store.Web/Controllers/ProductCategoryController.cs
using Store.Model.Abstract.Service;
using Store.Model.Entities.dbml;
using System.Linq;
using System.Web.Mvc;

namespace Store.Web.Controllers
{
    public class ProductCategoryController : BaseController<ProductCategory>
    {
        #region ctor
        public ProductCategoryController(IProductCategoryService service) : base(service) { }
        #endregion

        public ActionResult CategoryMenu(int? categoryId)
        {
            IQueryable<ProductCategory> model = service.GetAll().Where(x => x.Products.Any());

            ViewBag.SelectedCategoryId = categoryId;

            return PartialView(model);
        }
    }
}

Store.Web/Controllers/ProductController.cs
using Store.Model.Abstract.Service;
using Store.Model.Entities.dbml;
using Store.Model.Entities.Helpers;
using System.Linq;
using System.Web.Mvc;

namespace Store.Web.Controllers
{
    public class ProductController : BaseController<Product>
    {
        private const int PageSize = 2;

        #region ctor
        public ProductController(IProductService service) : base(service) { }
        #endregion

        public ActionResult List(int categoryId, int page = 1)
        {
            var list = ((IProductService)service).GetProductsByCategoryId(categoryId);

            PagingInfo pgInfo = new PagingInfo
            {
                CurrentPage = page,
                ItemsPerPage = PageSize,
                TotalItems = list.Count()
            };

            var model = list.Skip((page - 1) * PageSize).Take(PageSize);

            ViewData["PageInfo"] = pgInfo;
            return View(model);
        }

        public ViewResult InsertInCart(int? productId)
        {
            Cart cart = (Cart)Session["Cart"] ?? new Cart();
            if (productId.HasValue)
                cart.AddItem(service.GetById(productId.Value), 1);
            Session["Cart"] = cart;
            return View("CartSummary", cart);
        }

        public ActionResult ClearCart()
        {
            Session["Cart"] = new Cart();
            return Content("Good");
        }

        public ViewResult CartSummary()
        {
            Cart cart = (Cart)Session["Cart"] ?? new Cart();
            return View(cart);
        }
    }
}

Store.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <div id="header">
        <div id="divCart">
            @{Html.RenderAction("CartSummary", "Product");}
        </div>
        <div class="title">МАГАЗИН</div>
    </div>
    <div id="categories">
        @{Html.RenderAction("CategoryMenu", "ProductCategory"); }
    </div>
    <div id="content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jGrid")
    @RenderSection("scripts", required: false)
</body>
</html> 